- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 86400 #One day`
    - name: Install system
      action: apt pkg={{item}} state=installed
      with_items:
        - xorg
        - i3
        - lightdm
        - chromium-browser
        - build-essential
        - git
    - name: Enable lightdm
      systemd:
        name: lightdm
        state: started
        enabled: True 
